### PR TITLE
fix(watermarker): update TextWatermarkerBuilder validation for StartEnd strategy

### LINKED ISSUE #127: TextWatermarkerBuilder incorrectly validates for StartEndSeparatorChars strategy
# 🐞 Bug Report

## Describe the Bug
The validate function of the TextWatermarkerBuilder checks whether the start Char of the StartEndSeparatorChars SeparatorStrategy is contained in the transcoding alphabet twice instead of first checking the start Char and then the end Char.

## To Reproduce
1. Build a TextWatermarker using the Builder with the StartEndSeparatorChars strategy and make the end Char any Char of the transcoding alphabet
2. The validate function returns a Status.Success 

## Expected Behavior
The validate function should return an Event.Error of type AlphabetContainsSeparatorError

## System Information
 - Component: watermarker
 - Runtime: java 17 on ubuntu 24.04 LTS

### PR DESCRIPTION
**Pull request by Schiphorst-ISST**
## Description
Update the TextWatermarkerBuilder class's validate function in TextWatermarker file to correctly check both Chars in the StartEnd strategy as well as adding corresponding test in TextWatermarkerTest.

## Linked Issue(s)
Fixes #127 

## CLA
By submitting this pull request, I have read the [Corporate Contributor License Agreement (CLA)](https://github.com/FraunhoferISST/TREND/blob/main/CLA.md) and I hereby accept and sign the CLA.

### CODE REVIEW

File: watermarker/src/commonTest/kotlin/unitTest/fileWatermarker/TextWatermarkerTest.kt [hunk 1]
```diff
@@ -206,6 +206,64 @@ class TextWatermarkerBuilderTest {
         assertNull(result.value)
     }
 
+    /**
+     * tests if the validate() function of the builder will correctly return an error when
+     * either Separator in the StartEnd Strategy is an illegal Char, as well as when both the
+     * Start and End Char are illegal
+     */
```
Comment (mhellmeier) [inline watermarker/src/commonTest/kotlin/unitTest/fileWatermarker/TextWatermarkerTest.kt]: Writing comments for functions is always good. But since we decided to not comment any tests, this comment should be deleted to have a uniform code.

**Review by mhellmeier — CHANGES_REQUESTED** [review]
Just a small hint

**Review by mhellmeier — APPROVED** [review]
